-- PRUEBAS.PERSONA definition

CREATE TABLE "PRUEBAS"."PERSONA" 
   (    "ID" NUMBER(*,0), 
    "NOMBRE" VARCHAR2(100), 
    "APELLIDO_MATERNO" VARCHAR2(100), 
    "APELLIDO_PATERNO" VARCHAR2(100), 
     CONSTRAINT "PERSONA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PRUEBAS"."PERSONA_PK" ON "PRUEBAS"."PERSONA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- PRUEBAS.LINEA_TELEFONICA definition

CREATE TABLE "PRUEBAS"."LINEA_TELEFONICA" 
   (    "ID" NUMBER(10,0), 
    "NUMERO_TELEFONICO" VARCHAR2(10), 
    "SMS" NUMBER(1,0), 
    "LLAMADAS" NUMBER(1,0), 
    "FACEBOOK" NUMBER(1,0), 
    "WHATSAPP" NUMBER(1,0), 
    "ID_PERSONA" NUMBER, 
    "PERSONA_ID" NUMBER(19,0) NOT NULL ENABLE, 
     CONSTRAINT "LINEA_TELEFONICA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "PRUEBAS"."LINEA_TELEFONICA" ADD CONSTRAINT "FK_PERSONA" FOREIGN KEY ("ID_PERSONA")
      REFERENCES "PRUEBAS"."PERSONA" ("ID") ENABLE;
  ALTER TABLE "PRUEBAS"."LINEA_TELEFONICA" ADD CONSTRAINT "FKDTVFIVOTI08GKGYP0TS30J0EN" FOREIGN KEY ("PERSONA_ID")
      REFERENCES "PRUEBAS"."PERSONA" ("ID") ENABLE;

CREATE UNIQUE INDEX "PRUEBAS"."LINEA_TELEFONICA_PK" ON "PRUEBAS"."LINEA_TELEFONICA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;